### PR TITLE
Support transforms on schemas (Closes #120)

### LINKED ISSUE #120: Support for Zod Schema `.transform`
Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@asteasolutions/zod-to-openapi@4.5.3` for the project I'm working on.

I wanted to use `.transform()` for my zod schema, which broke the openapi generator. Here's an example:
```typescript
limit: z
    .number()
    .optional()
    .openapi({
      description: "Number of results to return. Always default to 3 unless specified otherwise by the user.",
      type: "integer",
    })
    .default(3)
    .transform((v) => v.toString())
```

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js b/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
index d82c957..23f5a53 100644
--- a/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
+++ b/node_modules/@asteasolutions/zod-to-openapi/dist/openapi-generator.js
@@ -641,7 +641,7 @@ class OpenAPIGenerator {
             return this.unwrapChained(schema._def.innerType);
         }
         if ((0, zod_is_type_1.isZodType)(schema, 'ZodEffects') &&
-            schema._def.effect.type === 'refinement') {
+           ['refinement', 'transform'].includes(schema._def.effect.type)) {
             return this.unwrapChained(schema._def.schema);
         }
         return schema;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

Happy to turn this into the PR if you approve of the suggestion

### PR DESCRIPTION
**Pull request by dvargas92495**

### CODE REVIEW

**Comment by dvargas92495** [comment]
I'm unable to add a reviewer, so tagging @AGalabov for review

**Review by AGalabov — COMMENTED** [review]
@dvargas92495 thank you for raising this PR. I left a small comment about refactoring the test case. As a side note, the checks seem to be failing on `npm run lint`? You can run: `npm run prettier` and that should fix the issue for you

**Comment by AGalabov** [comment]
@dvargas92495  this has just been merged through [this PR](https://github.com/asteasolutions/zod-to-openapi/pull/136) so I'll be closing yours, sorry.

**Comment by dvargas92495** [comment]
Great news! Thanks for getting it across the finish line

**Pull request closed without merging**
