### PR TITLE
Add 'head', 'options', and 'trace' to Method type in OpenAPI registry

### PR DESCRIPTION
**Pull request by dankors**
Thank you for maintaining this excellent repository! I'm working on a project that uses the OPTIONS verb and needed to expand the list of available methods. Cheers.

`type Method = 'get' | 'post' | 'put' | 'delete' | 'patch' | 'head' | 'options' | 'trace';`

### CODE REVIEW

**Review by samchungy — APPROVED** [review]

**Review by AGalabov — APPROVED** [review]
@dankors thank you for the kind words and the contribution.

**Comment by AGalabov** [comment]
@dankors I ran the checks and they failed - probably because of prettier - the new line has gotten too long. There is an `npm run prettier` script that you can utilize to fix it.

**Comment by dankors** [comment]
@AGalabov Just ran the prettier script - Should be fixed now!

**Comment by AGalabov** [comment]
@dankors thank you. Your fix is now available in [v4.4.3](https://github.com/asteasolutions/zod-to-openapi/releases/tag/v4.4.3)

**Pull request merged**
