### PR TITLE
Expose the RouteConfig interface (proposal)

### LINKED ISSUE #32: Expose RouteConfig from openapi-registry
I am looking to build helper functions for controlling access to the registry, and having all the logic centralized.

I'd like my helper function to take in the RouteConfig as a parameter. Having access to your RouteConfig would be helpful here, so I don't have to mimic the type.

I made a quick edit in my local code base and it seems to work fine, by just adding RouteConfig to the export.

Let me know what you think! Thanks!

https://github.com/asteasolutions/zod-to-openapi/blob/fdf240a40182d2c8cd7797bc891f67d3c2a04314/src/index.ts#L3

### PR DESCRIPTION
**Pull request by Fish1**
PR Example of what I am looking for.

closes #32

### CODE REVIEW

**Comment by AGalabov** [comment]
Looks good

**Comment by Fish1** [comment]
I've only exposed the interfaces I personally needed at the moment. Do you think it would be helpful to expose all the parameter interfaces?

A common patter I use is...
```ts
const myParam: Type = {
  blah: 1,
  test: 2,
}

doStuff(myParam);
```

So maybe just exposing all of the parameters would be a nice to have.

**Comment by AGalabov** [comment]
@Fish1 I am okay with exporting `ResponseConfig` as well. The others are more of an internal implementation types.

**Comment by AGalabov** [comment]
@Fish1 I see that the build checks are failing. Can you check if the code is formatted properly. You can check try and run `npm run lint`. I imagine that the export would be reordered into a multiline one.

**Comment by Fish1** [comment]
I checked the linter and ran prettier to properly format the code.

**Pull request merged**
